### ISSUE TITLE
Can't get multiple line on same chart

### ISSUE THREAD

**Issue by Grahamrich1** [SilverBirchh/MMM-TFL#2]
Hi,
I've tried to get multiple lines on the same chart but struggling.
{
			module: "MMM-TFL",
			position: "top_left",
			config: {
			lines: 'central',
			lines: 'jubilee',
			lines: 'victoria',
			updateTime: 60000,
			app_id: null,
			app_key: null}

		},

This provided something on the screen (MMM) but only for the victoria line.

I got this to work by loading the module for each line.  Looks messy on the screen

{
			module: "MMM-TFL",
			position: "top_left",
			config: {
			lines: 'central',
			updateTime: 60000,
			app_id: null,
			app_key: null}

		},	{
			module: "MMM-TFL",
			position: "top_left",
			config: {
			lines: 'jubilee',
			updateTime: 60000,
			app_id: null,
			app_key: null}

		},{
			module: "MMM-TFL",
			position: "top_left",
			config: {
			lines: 'victoria',
			updateTime: 60000,
			app_id: null,
			app_key: null}

		},

**Comment by Grahamrich1** [comment]
Ops,  Ok I've read the readme again and updated as follows:  Multiple lines working now.

{
			module: "MMM-TFL",
			position: "top_left",
			config: {
			lines: ['bakerloo', 'central', 'circle', 'victoria'],
			updateTime: 60000,
			app_id: null,
			app_key: null}

		},

**Comment by SilverBirchh** [comment]
Glad you got it working. If you think the readme is a little unclear feel free to raise a PR 😄

**Comment by Grahamrich1** [comment]
Hi,

Thanks for your reply.  I'm relatively new to Github and Im not sure what a PR is.   I will read up and raise it later

Regards
Graham

On Sep 17, 2018, at 12:42 PM, Bradley Birch <notifications@github.com> wrote:

Glad you got it working. If you think the readme is a little unclear feel free to raise a PR 😄
